name: Test and clean code

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install dependencies
        run: make install-dev
      - name: Fix with Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: 'check --fix'
      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: 'format'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style fixes by ruff'

  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install dependencies
        run: make install-dev
      - name: Test with pytest
        run: pytest --junitxml=junit/test-results.xml --cov-report term --cov-report xml:coverage.xml --cov
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}
      - name: Code Coverage Summary Report
        id: coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '85 90'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Update README.md
        run: |
          badge=$(head -n 1 code-coverage-results.md)
          echo $badge
          sed -i "2s|.*|${badge}|" README.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'update coverage badge on README.md'
          file_pattern: "README.md"

          