"""Adicionar data_de_nascimento na tabela usuarios

Revision ID: 19687d265673
Revises: 9c3ea4f8559a
Create Date: 2025-01-10 16:58:13.843745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19687d265673'
down_revision: Union[str, None] = '9c3ea4f8559a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('data_de_nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'data_de_nascimento')
    # ### end Alembic commands ###
